config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get '/english', to: 'pages#english'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Félix Timmel : Portfolio</title>
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= image_url "meta_img.png" %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= image_url "meta_img.png" %>">

    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= favicon_link_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>

    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/english.html.erb
<div class="main_container">
  <div class="about_me">
    <span class="heading underline">Full Stack Developer</span>
    <div class="flex">
      <div class="description">
        <p>
          Hi, I'm Félix, web developer located in Paris. <br>
          After my master in digital marketing, I went to Montreal to discover the coding word by following the <a href="https://www.lewagon.com/fr/montreal/web-development-course/full-time" target="_blank" style="color: #ff0059">Le wagon</a> bootcamp.
        </p>
        <p id="cv"><%= link_to "📋 My CV 👈", asset_path("CV-2020-Web-dev-EN.pdf"), target: "_blank" %></p>
        <p id="cv"><%= link_to "💻 My Github Profil 👈", 'https://github.com/felixtimmel', target: "_blank" %></p>
      </div>
      <div class="description_image">
        <img src="<%= image_url "profil_pic.jpg" %>" alt="proile image" class="profile_avatar">
      </div>
    </div>
  </div>
</div>

<div class="projects" id="projets">
  <div class="main_container">
    <div class="project_grid">

      <div class="project_card">
        <div class="project_img">
          <img src="<%= image_url "Oveo.PNG" %>" alt="oveo image">
        </div>
        <div class="project_card_content">
          <div>
            <p style="font-size: small;">Responsive mobile site / React.js</p>
            <p>
              Oveo is a platform to find the lyrics of your music <br>  
              The platform works through your Spotify account, making calls to the API and SDK, as well as the Genius API to retrieve the lyrics of the songs.
            </p>
          </div>
          <div class="project_link">
            <p><%= link_to "View project", "https://music-lyrics-8b137.firebaseapp.com/", target: "_blank" %></p>
          </div>
        </div>
      </div>

      <div class="project_card">
        <div class="project_img">
          <img src="<%= image_url "began-homepage.png" %>" alt="began image">
        </div>
        <div class="project_card_content">
          <div>
            <p style="font-size: small;">Mobile site / Ruby</p>
            <p>
              Began is a web-app which aims to guide you towards a vegan diet. <br>
              This is the final project of my 9 week bootcamp.
            </p>
          </div>
          <div class="project_link">
            <p><%= link_to "View project", "http://www.began.fun/", target: "_blank" %></p>
          </div>
        </div>
      </div>

      <div class="project_card">
        <div class="project_img">
          <img src="<%= image_url "ctstudio-pic.png" %>" alt="ct-studio image">
        </div>
        <div class="project_card_content">
          <div>
            <p style="font-size: small;">Website / Ruby</p>
            <p>ct-studio : Market place for designs</p>
            <p style="font-size: small;">
              To login without having to create an account: <br>
              Email : felix@web.com
              password : 123456
            </p>
          </div>
          <div class="project_link">
            <p><%= link_to "View project", "https://ctstudio.herokuapp.com/", target: "_blank" %></p>
          </div>
        </div>
      </div>

      <div class="project_card">
        <div class="project_img">
          <img src="<%= image_url "cocktail-homepage.png" %>" alt="cocktailitos image">
        </div>
        <div class="project_card_content">
          <div>
            <p style="font-size: small;">Website / Ruby</p>
            <p>Cocktailitos : A cocktail platform for applying CRUD operations intended for data persistence.</p>
          </div>
          <div class="project_link">
            <p><%= link_to "View project", "https://misses-cocktail-batch367.herokuapp.com/", target: "_blank" %></p>
          </div>
        </div>
      </div>

    </div>
    <div class="project_content">
      <p class="heading">
        Projects
      </p>
      <ul class="list">
        <div class="project_row">
          <li class="item"><i class="far fa-circle"></i> Conception</li>
          <li class="item"><i class="far fa-circle"></i> Design</li>
        </div>
        <div class="project_row">
          <li class="item"><i class="far fa-circle"></i> Production</li>
          <li class="item"><i class="far fa-circle"></i> Team work</li>
        </div>
      </ul>
    </div>
  </div>
</div>

<div class="main_container">
  <div class="skills" id="skills">
    <p class="heading">Skills</p>
    <div class="skill_grid">
      <p class="skills_box">Ruby on Rails</p>
      <p class="skills_box">React.js</p>
      <p class="skills_box">APIs, JSON, scraping</p>
      <p class="skills_box">Databases, SQL, Postgres</p>
      <p class="skills_box">HTML, CSS, Bootstrap</p>
      <p class="skills_box">ES6 Javascript</p>
      <p class="skills_box">Wireframes, prototyping </p>
      <p class="skills_box">UX / UI design</p>
      <p class="skills_box">Test driven development</p>
      <p class="skills_box">Git, Github</p>
      <p class="skills_box">Technical workflow</p>
    </div>
  </div>
  <div class="skills" id="skills">
    <p class="heading">Currently learning :</p>
    <div class="skill_grid">
      <p class="skills_box">React</p>
      <p class="skills_box">Redux</p>
      <p class="skills_box">Firebase</p>
      <p class="skills_box">Node.js</p>
    </div>
  </div>
</div>

<div class="chat" id="contact">
  <div class="main_container">
    <div class="chat_content">
      <p class="heading">Let's chat</p>
      <p>
        I'm always interested about learning new stuff <br>
        And talking is what gather us
      </p>
      <div class="chat_btn">
        <a class="mailto" href="mailto:felix.timmel@hotmail.fr">
          <button class="button">Contact me !</button>
        </a>
      </div>
      <div class="chat_links">
        <%= link_to "https://www.linkedin.com/in/felixtimmel/", target: "_blank" do %>
          <p class="links_container"><i class="fab fa-linkedin"></i></p>
        <% end %>
        <%= link_to "https://github.com/felixtimmel", target: "_blank" do %>
          <p class="links_container"><i class="fab fa-github-square"></i></p>
        <% end %>
        <p class="links_container"><i class="fas fa-phone-square" data-toggle="modal" data-target="#phoneModal"></i></p>
        <p class="links_container"><i class="fas fa-envelope-square" data-toggle="modal" data-target="#mailModal"></i></p>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="phoneModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Phone number</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        07 77 05 34 12
      </div>
      <div class="modal-footer">
        <button class="button" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="mailModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Email</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <ul>
          <li class="item">felix.timmel@hotmail.fr</li>
          <li class="item">f.timmel95@gmail.com</li>
        </ul>
      </div>
      <div class="modal-footer">
        <button class="button" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="main_container">
  <div class="about_me">
    <span class="heading underline">Full Stack Developer</span>

    <div class="flex">
      <div class="description">
        <p>
          Salut, moi c'est Félix, developer web situé sur Paris. <br>
          Après mon master en marketing digital, j'ai décidé d'approfondir mes compétences téchniques en allant suivre à Montreal une formation de développeur intensive de 9 semaines : <a href="https://www.lewagon.com/fr/montreal/web-development-course/full-time" target="_blank" style="color: #ff0059">Le wagon</a>.
        </p>
        <p id="cv"><%= link_to "📋 Mon CV 👈", asset_path("CV-2020-Web-dev-FR.pdf"), target: "_blank" %></p>
        <p id="cv"><%= link_to "💻 Mon profil Github 👈", 'https://github.com/felixtimmel', target: "_blank" %></p>
      </div>
      <div class="description_image">
        <img src="<%= image_url "profil_pic.jpg" %>" alt="proile image" class="profile_avatar">
      </div>
    </div>

  </div>
</div>

<div class="projects" id="projets">
  <div class="main_container">
    <div class="project_grid">
      <div class="project_card">
        <div class="project_img">
          <img src="<%= image_url "banner.jpg" %>" alt="dofuskin image">
        </div>
        <div class="project_card_content">
          <div>
            <p style="font-size: small;">Responsive mobile site / Webflow</p>
            <p>
              DofuSkins est un site réalisé sur Webflow <br>
              Un site concernant l'univers de mon jeu vidéo favori.
            </p>
          </div>
          <div class="project_link">
            <p><%= link_to "View project", "https://dofuskin.com/", target: "_blank" %></p>
          </div>
        </div>
      </div>
      <div class="project_card">
        <div class="project_img">
          <img src="<%= image_url "Oveo.PNG" %>" alt="oveo image">
        </div>
        <div class="project_card_content">
          <div>
            <p style="font-size: small;">Responsive web app / React.js</p>
            <p>
              Oveo est une platforme pour trouver les paroles de vos musiques <br>
              La platforme fonctionne grâce à votre compte Spotify, en faisant des appels à l'API et au SDK, ainsi qu'à  l'API de Genius pour récuperer les paroles des chansons.
            </p>
          </div>
          <div class="project_link">
            <p><%= link_to "View project", "https://music-lyrics-8b137.firebaseapp.com/", target: "_blank" %></p>
          </div>
        </div>
      </div>

      <div class="project_card">
        <div class="project_img">
          <img src="<%= image_url "began-homepage.png" %>" alt="began image">
        </div>
        <div class="project_card_content">
          <div>
            <p style="font-size: small;">Web app / Ruby</p>
            <p>
              Began est une web-app qui a pour but de vous guider vers une alimentation vegan. <br>
              C'est le projet finale de mon bootcamp de 9 semaines.
            </p>
          </div>
          <div class="project_link">
            <p><%= link_to "View project", "http://www.began.fun/", target: "_blank" %></p>
          </div>
        </div>
      </div>

      <div class="project_card">
        <div class="project_img">
          <img src="<%= image_url "ctstudio-pic.png" %>" alt="ct-studio image">
        </div>
        <div class="project_card_content">
          <div>
            <p style="font-size: small;">Website / Ruby</p>
            <p>ct-studio : Market place pour designs</p>
            <p style="font-size: small;">
              Pour consulter l'application sans avoir à créer de compte : <br>
              Email : felix@web.com
              password : 123456
            </p>
          </div>
          <div class="project_link">
            <p><%= link_to "View project", "https://ctstudio.herokuapp.com/", target: "_blank" %></p>
          </div>
        </div>
      </div>

      <div class="project_card">
        <div class="project_img">
          <img src="<%= image_url "cocktail-homepage.png" %>" alt="cocktailitos image">
        </div>
        <div class="project_card_content">
          <div>
            <p style="font-size: small;">Website / Ruby</p>
            <p>Cocktailitos : Une platforme de cocktails pour appliquer les opérations CRUD déstinées à la persistance des données.</p>
          </div>
          <div class="project_link">
            <p><%= link_to "View project", "https://misses-cocktail-batch367.herokuapp.com/", target: "_blank" %></p>
          </div>
        </div>
      </div>

    </div>
    <div class="project_content">
      <p class="heading">
        Projets
      </p>
      <ul class="list">
        <div class="project_row">
          <li class="item"><i class="far fa-circle"></i> Conception</li>
          <li class="item"><i class="far fa-circle"></i> Prototypage</li>
        </div>
        <div class="project_row">
          <li class="item"><i class="far fa-circle"></i> Mise en production</li>
          <li class="item"><i class="far fa-circle"></i> Travail en équipe</li>
        </div>
      </ul>
    </div>
  </div>
</div>

<div class="main_container">
  <div class="skills" id="skills">
    <p class="heading">Skills</p>
    <div class="skill_grid">
      <p class="skills_box">Ruby on Rails</p>
      <p class="skills_box">React.js</p>
      <p class="skills_box">Webflow</p>
      <p class="skills_box">APIs, JSON, scraping</p>
      <p class="skills_box">Databases, SQL, Postgres</p>
      <p class="skills_box">HTML, CSS, Bootstrap</p>
      <p class="skills_box">ES6 Javascript</p>
      <p class="skills_box">Wireframes, prototyping </p>
      <p class="skills_box">UX / UI design</p>
      <p class="skills_box">Test driven development</p>
      <p class="skills_box">Git, Github</p>
      <p class="skills_box">Technical workflow</p>
    </div>
  </div>
  <div class="skills" id="skills">
    <p class="heading">Ce que j'apprend en ce moment :</p>
    <div class="skill_grid">
      <p class="skills_box">React.js</p>
      <p class="skills_box">Flutter</p>
      <p class="skills_box">Firebase</p>
      <p class="skills_box">Webflow</p>
    </div>
  </div>
</div>

<div class="chat" id="contact">
  <div class="main_container">
    <div class="chat_content">
      <p class="heading">Let's chat</p>
      <p>
        Je suis toujours intéressé pour apprendre de nouvelles choses <br>
        Et parler de nouvelles idées...
      </p>
      <div class="chat_btn">
        <a class="mailto" href="mailto:felix.timmel@hotmail.fr">
          <button class="button">Contactez moi !</button>
        </a>
      </div>
      <div class="chat_links">
        <%= link_to "https://www.linkedin.com/in/felixtimmel/", target: "_blank" do %>
          <p class="links_container"><i class="fab fa-linkedin"></i></p>
        <% end %>
        <%= link_to "https://github.com/felixtimmel", target: "_blank" do %>
          <p class="links_container"><i class="fab fa-github-square"></i></p>
        <% end %>
        <p class="links_container"><i class="fas fa-phone-square" data-toggle="modal" data-target="#phoneModal"></i></p>
        <p class="links_container"><i class="fas fa-envelope-square" data-toggle="modal" data-target="#mailModal"></i></p>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="phoneModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Phone number</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        07 77 05 34 12
      </div>
      <div class="modal-footer">
        <button class="button" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="mailModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Email</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <ul>
          <li class="item">felix.timmel@hotmail.fr</li>
          <li class="item">f.timmel95@gmail.com</li>
        </ul>
      </div>
      <div class="modal-footer">
        <button class="button" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar">
  <div class="logo">
    <%= link_to "Félix Timmel", root_path %>
  </div>

  <div class="navbar_links">
    <div class="text_links">
      <%= link_to "Portfolio", root_path(anchor: 'projets') %>
      <%= link_to "Compétences", root_path(anchor: 'skills') %>
      <%= link_to "Contact", root_path(anchor: 'contact') %>
    </div>
    <span>
    <%= link_to root_path do %>
    🇫🇷
    <% end %>
  |
    <%= link_to english_path do %>
    🇬🇧
    <% end %>
  </span>
  </div>
</div>